-- GTCC 관리자용 Supabase 스키마
-- Supabase SQL Editor에서 전체를 한 번 실행합니다.

create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '관리자',
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  category text not null,
  group_key text not null check (group_key in ('popular', 'new', 'middle', 'career', 'pass')),
  image_url text not null,
  tags text[] not null default '{}',
  summary text not null default '',
  curriculum text[] not null default '{}',
  duration text not null default '4주',
  exam_type text not null default '온라인시험',
  benefit_label text not null default '장학지원',
  sort_order integer not null default 0,
  published boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notices (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity unique,
  title text not null,
  body text not null default '',
  image_url text,
  link_url text,
  link_label text,
  author text not null default 'GTCC대학교평생교육원',
  published_at date not null default current_date,
  published boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 이미 운영 중인 프로젝트에서도 공지 이미지와 링크 컬럼만 안전하게 추가합니다.
alter table public.notices add column if not exists image_url text;
alter table public.notices add column if not exists link_url text;
alter table public.notices add column if not exists link_label text;

create table if not exists public.slides (
  id uuid primary key default gen_random_uuid(),
  image_url text not null,
  alt_text text not null,
  sort_order integer not null default 0,
  published boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_history (
  id bigint generated always as identity primary key,
  entity_type text not null check (entity_type in ('courses', 'notices', 'slides')),
  entity_id uuid not null,
  action text not null check (action in ('insert', 'update', 'delete', 'restore')),
  before_data jsonb,
  after_data jsonb,
  actor_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists courses_public_idx on public.courses (published, deleted_at, group_key, sort_order);
create index if not exists notices_public_idx on public.notices (published, deleted_at, published_at desc);
create index if not exists slides_public_idx on public.slides (published, deleted_at, sort_order);
create index if not exists history_recent_idx on public.content_history (created_at desc);

create or replace function public.is_gtcc_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.audit_content_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  action_name text;
begin
  if tg_op = 'INSERT' then
    action_name := 'insert';
    insert into public.content_history(entity_type, entity_id, action, before_data, after_data, actor_id)
    values (tg_table_name, new.id, action_name, null, to_jsonb(new), auth.uid());
    return new;
  end if;

  if old.deleted_at is null and new.deleted_at is not null then
    action_name := 'delete';
  elsif old.deleted_at is not null and new.deleted_at is null then
    action_name := 'restore';
  else
    action_name := 'update';
  end if;

  insert into public.content_history(entity_type, entity_id, action, before_data, after_data, actor_id)
  values (tg_table_name, new.id, action_name, to_jsonb(old), to_jsonb(new), auth.uid());
  return new;
end;
$$;

drop trigger if exists courses_touch_updated_at on public.courses;
create trigger courses_touch_updated_at before update on public.courses
for each row execute function public.touch_updated_at();
drop trigger if exists courses_audit on public.courses;
create trigger courses_audit after insert or update on public.courses
for each row execute function public.audit_content_change();

drop trigger if exists notices_touch_updated_at on public.notices;
create trigger notices_touch_updated_at before update on public.notices
for each row execute function public.touch_updated_at();
drop trigger if exists notices_audit on public.notices;
create trigger notices_audit after insert or update on public.notices
for each row execute function public.audit_content_change();

drop trigger if exists slides_touch_updated_at on public.slides;
create trigger slides_touch_updated_at before update on public.slides
for each row execute function public.touch_updated_at();
drop trigger if exists slides_audit on public.slides;
create trigger slides_audit after insert or update on public.slides
for each row execute function public.audit_content_change();

alter table public.admin_users enable row level security;
alter table public.courses enable row level security;
alter table public.notices enable row level security;
alter table public.slides enable row level security;
alter table public.content_history enable row level security;

drop policy if exists "admin users read own profile" on public.admin_users;
create policy "admin users read own profile" on public.admin_users
for select using (user_id = auth.uid());

drop policy if exists "public reads published courses" on public.courses;
create policy "public reads published courses" on public.courses
for select using (published = true and deleted_at is null);
drop policy if exists "admins manage courses" on public.courses;
create policy "admins manage courses" on public.courses
for all using (public.is_gtcc_admin()) with check (public.is_gtcc_admin());

drop policy if exists "public reads published notices" on public.notices;
create policy "public reads published notices" on public.notices
for select using (published = true and deleted_at is null);
drop policy if exists "admins manage notices" on public.notices;
create policy "admins manage notices" on public.notices
for all using (public.is_gtcc_admin()) with check (public.is_gtcc_admin());

drop policy if exists "public reads published slides" on public.slides;
create policy "public reads published slides" on public.slides
for select using (published = true and deleted_at is null);
drop policy if exists "admins manage slides" on public.slides;
create policy "admins manage slides" on public.slides
for all using (public.is_gtcc_admin()) with check (public.is_gtcc_admin());

drop policy if exists "admins read history" on public.content_history;
create policy "admins read history" on public.content_history
for select using (public.is_gtcc_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('site-media', 'site-media', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public reads site media" on storage.objects;
create policy "public reads site media" on storage.objects
for select using (bucket_id = 'site-media');
drop policy if exists "admins upload site media" on storage.objects;
create policy "admins upload site media" on storage.objects
for insert with check (bucket_id = 'site-media' and public.is_gtcc_admin());
drop policy if exists "admins update site media" on storage.objects;
create policy "admins update site media" on storage.objects
for update using (bucket_id = 'site-media' and public.is_gtcc_admin());
drop policy if exists "admins delete site media" on storage.objects;
create policy "admins delete site media" on storage.objects
for delete using (bucket_id = 'site-media' and public.is_gtcc_admin());

create or replace function public.restore_content_version(history_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  history_row public.content_history;
begin
  if not public.is_gtcc_admin() then
    raise exception '관리자 권한이 필요합니다.';
  end if;

  select * into history_row from public.content_history where id = history_id;
  if history_row.id is null then
    raise exception '변경 기록을 찾을 수 없습니다.';
  end if;

  if history_row.before_data is null then
    execute format(
      'update public.%I set published = false, deleted_at = now() where id = $1',
      history_row.entity_type
    ) using history_row.entity_id;
    return;
  end if;

  if history_row.entity_type = 'courses' then
    insert into public.courses
    select * from jsonb_populate_record(null::public.courses, history_row.before_data)
    on conflict (id) do update set
      slug = excluded.slug,
      title = excluded.title,
      category = excluded.category,
      group_key = excluded.group_key,
      image_url = excluded.image_url,
      tags = excluded.tags,
      summary = excluded.summary,
      curriculum = excluded.curriculum,
      duration = excluded.duration,
      exam_type = excluded.exam_type,
      benefit_label = excluded.benefit_label,
      sort_order = excluded.sort_order,
      published = excluded.published,
      deleted_at = excluded.deleted_at;
  elsif history_row.entity_type = 'notices' then
    insert into public.notices
    select * from jsonb_populate_record(null::public.notices, history_row.before_data)
    on conflict (id) do update set
      number = excluded.number,
      title = excluded.title,
      body = excluded.body,
      image_url = excluded.image_url,
      link_url = excluded.link_url,
      link_label = excluded.link_label,
      author = excluded.author,
      published_at = excluded.published_at,
      published = excluded.published,
      deleted_at = excluded.deleted_at;
  elsif history_row.entity_type = 'slides' then
    insert into public.slides
    select * from jsonb_populate_record(null::public.slides, history_row.before_data)
    on conflict (id) do update set
      image_url = excluded.image_url,
      alt_text = excluded.alt_text,
      sort_order = excluded.sort_order,
      published = excluded.published,
      deleted_at = excluded.deleted_at;
  end if;
end;
$$;

revoke all on function public.restore_content_version(bigint) from public;
grant execute on function public.restore_content_version(bigint) to authenticated;

-- 슬라이드 순서를 한 번의 트랜잭션으로 변경합니다.
create or replace function public.reorder_slides(slide_ids uuid[])
returns setof public.slides
language plpgsql
security definer
set search_path = public
as $$
declare
  slide_id uuid;
  slide_position integer := 0;
begin
  if not public.is_gtcc_admin() then
    raise exception '관리자 권한이 필요합니다.';
  end if;

  foreach slide_id in array slide_ids loop
    update public.slides
    set sort_order = slide_position * 10
    where id = slide_id and deleted_at is null;
    slide_position := slide_position + 1;
  end loop;

  return query
  select * from public.slides
  where id = any(slide_ids) and deleted_at is null
  order by sort_order;
end;
$$;

revoke all on function public.reorder_slides(uuid[]) from public;
grant execute on function public.reorder_slides(uuid[]) to authenticated;

-- 기존 공지번호를 이관한 뒤 다음 자동 번호가 최댓값 다음부터 시작하게 맞춥니다.
create or replace function public.sync_notice_number_sequence()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  next_number bigint;
begin
  if not public.is_gtcc_admin() then
    raise exception '관리자 권한이 필요합니다.';
  end if;

  select coalesce(max(number), 0) + 1 into next_number from public.notices;
  perform setval(pg_get_serial_sequence('public.notices', 'number'), next_number, false);
end;
$$;

revoke all on function public.sync_notice_number_sequence() from public;
grant execute on function public.sync_notice_number_sequence() to authenticated;

-- 휴지통에서 30일이 지난 콘텐츠를 영구 삭제합니다.
create or replace function public.purge_deleted_content()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() <> 'service_role' and not public.is_gtcc_admin() then
    raise exception '관리자 권한이 필요합니다.';
  end if;

  delete from public.courses where deleted_at < now() - interval '30 days';
  delete from public.notices where deleted_at < now() - interval '30 days';
  delete from public.slides where deleted_at < now() - interval '30 days';
end;
$$;

revoke all on function public.purge_deleted_content() from public;
grant execute on function public.purge_deleted_content() to authenticated;

-- Auth > Users에서 두 관리자 계정을 만든 뒤 아래 두 줄의 UUID와 이름을 바꿔 실행합니다.
-- insert into public.admin_users(user_id, display_name) values ('사용자-UUID', '운영자');
-- insert into public.admin_users(user_id, display_name) values ('아버님-UUID', '관리자');
